version: '3.3'

services:

# ======================================================================
# Web Server
# ======================================================================

  main:
    image: nginx:1.12.2-alpine
    container_name: example-main
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
     - VIRTUAL_HOST=localhost
     - VIRTUAL_PORT=80
     - NGINX_HOST=localhost
     - NGINX_PORT=80
     - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - frontend_network

networks:
  frontend_network: